### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ch4m17ux** [anthares101/kali_volatility_installer#1]
Hola, agradezco tu script, pero he seguido los pasos descritos y no encuentro la falla de porque no instala correctamente.

He instalado los paquetes de sudo apt install python-dev y he lanzado el script correspondiente, pero me arroja:

kali@kali:~/Descargas$ ./install_volatility.sh 
Removing previous volatility installations...   [DONE]
Clone volatility to your home folder...         [DONE]
Installing pip for python 2...                  [DONE]
**Installing dependencies...                      [ERROR]**
Create bash script for execution...             [DONE]
Add volatility to path...                       [DONE]

All done! Some errors during installation, maybe volatility dont work as expected

He intentado lanzarlo con sudo y tambien sin sudo, que dependencias estarian faltando?

Gracias por tomarte el tiempo de leer mi "issue".

**Comment by anthares101** [comment]
Buenas! En principio no debería hacer falta ejecutar nada con sudo, por ir eliminando posibles problemas ¿tras ejecutar el script puedes ejecutar pip2 por ejemplo?

**Comment by ch4m17ux** [comment]
Hola

Gracias, Si puedo ejecutar `pip2`, incluso ejecutar `volatility2`, pero al hacer esto ultimo me saltan los errores de dependencias (que ya habia visto al tratar de hacerlo con otros medios)

```
ch4m0@kali:~$ volatility2
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
```

Por esta razon, queria probar tu metodo. Muchas gracias.

**Comment by ch4m17ux** [comment]
Hola

He podido verificar el bug, resulta que en tu codigo pones:

```
# Install pip for python 2 if necessary
echo -ne "Installing pip for python 2...\t\t\t"
if command -v pip2 &> /dev/null; then 
	echo -e "[${GREEN}DONE${NC}]"
else
	curl https://bootstrap.pypa.io/get-pip.py -o "${HOME}/volatility/get-pip.py" &> /dev/null
	python "${HOME}/volatility/get-pip.py" &> /dev/null
	printCommandResult
	exitOnError
	rm "${HOME}/volatility/get-pip.py"
fi
```

Pero en mi caso no instalaba `pip2` sino que se quedaba con `pip3` y al tratar de hacer:

```
# Install dependencies
echo -ne "Installing dependencies...\t\t\t"
pip2 install distorm3==3.4.4 yara-python pycrypto pillow openpyxl ujson &> /dev/null
printCommandResult
```
Me fallaba porque no reconocia el comando `pip2`.  Por lo que lo correcto seria hacer lo siguiente para instalar `pip2`:

`sudo python2 get-pip.py`

y posteriormente instalar las dependencias.

Muchas gracias por tu codigo.

**Comment by anthares101** [comment]
He mirado el problema que comentabas y creo que se lo que fallaba. No es necesario ejecutar con sudo ninguna parte del script pero si que es necesario que antes de ejecutarlo tengas `$HOME/.local/bin` en tu PATH como pone el `README` porque es donde se va a instalar pip2 al no usar `sudo` para ello.

Al usar `sudo pip2` la instalación se realiza a nivel de todo el sistema y no de usuario y por tanto, no es necesario tener la ruta de antes en el `PATH`, directamente `pip2` estaría disponible para su uso.

Es curioso porque en otras distros la ruta `$HOME/.local/bin` está por defecto en el PATH del usuario pero no en kali.
